apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gateway-role
rules:
  - apiGroups: ["faas.jashitha.dev"]
    resources: ["functions"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["faas.jashitha.dev"]
    resources: ["functions/status"]
    verbs: ["get", "patch", "update"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gateway-rolebinding
subjects:
  - kind: ServiceAccount
    name: gateway-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: gateway-role
  apiGroup: rbac.authorization.k8s.io
